### ISSUE TITLE
Custom data types with HCL queues

### ISSUE THREAD

**Issue by ctminh** [scs-lab/hcl#2] opened 2021-05-13 21:29 UTC
Hi, could I define a custom class/struct with hcl queue? For example, I tried to define (the configured hcl-mode is HCL_ENABLE_THALLIUM_ROCE):
```
typedef struct double_ptr_t {
    int size;
    double *A;  // ptr to the matrix A
    double *B;  // ptr to the matrix B
    double *C;  // ptr to the matrix C
       ... ...
} double_ptr_t;
```
Then, create an hcl-queue, i.e., mat_tasks_queue = new hcl::queue<double_ptr_t>(). For example, the example and its serialization here, https://github.com/ctminh/task-based-models-survey/blob/master/others/hcl_examples/queue_test/util.h#L64.
This was compiled ok but got the runtime error.

Another example, I followed your example and then try to create a struct of std::array<doulbe>, i.e., https://github.com/ctminh/task-based-models-survey/blob/master/others/hcl_examples/queue_test/util.h#L175. But something was wrong when I compile it:
```
... thallium/serialization/cereal/archives.hpp:112:31: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
112 |         ar.read(std::addressof(t), sizeof(t)); ...
```
So, did I miss something here? Do you have any suggestions?
Thanks!

**Comment by hariharan-devarajan** [comment] 2021-05-13 23:33
The double ptr is intended to be an unbounded array? or it is a fixed-sized array?
One thing to remember is you should never use pointers as pointers are allocated in the scope of the process in the heap. 
For unbounded array you can use std::vector or if you always have the same amount of elements or if you have an upper bound, you might use a std::array. In general std::array are faster than std::vector.

If you want to stick with points you may issues with shared memory access.

Also, you need a define a serialization mechanism using cereal. The serialization library used by thallium.
For serialization, you have to use cereal's binary serialization (it is the fastest).
```
boost::serialization::make_array<double>(A, 100);
```
This wont work as you have not set the serialized value in the archive. 
https://stackoverflow.com/questions/27518554/c-cereal-serialize-c-style-array
```
   ar( cereal::binary_data( A, sizeof(double) * 100 ) );
```
This will store the values in ar. The basic idea is to serialize your data structure using cereal stream and then store it in the archive.
If you want to pack and unpack yourself (I generally do that for complex types and complete control), you can define your own deserialization as well. https://uscilab.github.io/cereal/serialization_functions.html
In this use the save and load method.

**Comment by ctminh** [comment] 2021-05-14 16:34
Hi, thank you. I have tried again with the custom struct using std::array. Now, it works for compiling stuff, but somehow there was a runtime-error when trying to push custom-type elements to the hcl-queue. Maybe I need to turn the debug-flag on and figure out what happened there.

As you suggested, I used std::array, and added a readme to briefly describe the example which I am playing around. https://github.com/ctminh/task-based-models-survey/tree/master/others/hcl_examples/custom_queue_test.
This example is running 4 ranks, 2 ranks per node (R0, R1 on Node1, R2, R3 on Node2). I am setting R0 on Node 1 as the server, other ranks are clients. As I saw so far, R1, R2, R3 are trying to push the object into the queue, then it throws the runtime error.

Actually, I want to create a global queue of custom-struct types, e.g., can be called tasks (fixed-sized as usual). The use-case runs with multiple ranks on distributed nodes, each rank has multiple execution threads to perform the tasks. Like the scenario of task-stealing, the current rank could steal tasks from the other ranks. Instead of sending/receiving tasks with 2-sided-MPI operations, I want to try with HCL. So, how do you think? Does this make sense with HCL?

**Comment by hariharan-devarajan** [comment] 2021-05-14 17:35
> Actually, I want to create a global queue of custom-struct types, e.g., can be called tasks (fixed-sized as usual). The use-case runs with multiple ranks on distributed nodes, each rank has multiple execution threads to perform the tasks. Like the scenario of task-stealing, the current rank could steal tasks from the other ranks. Instead of sending/receiving tasks with 2-sided-MPI operations, I want to try with HCL. So, how do you think? Does this make sense with HCL?

What you can do is the following.
Rank 0 is the server and others are the clients.
Every rank should have the same server lists
```
HCL_CONF->SERVER_LIST_PATH = "./server_list";
``` 
Here generally, I use the format of mpich hostfile. for you as you have only one server, it would look like this.
```
server1
```
I see you are generating the server lists at https://github.com/ctminh/task-based-models-survey/blob/master/others/hcl_examples/custom_queue_test/custom_queue_test.cpp#L85
First you need a barrier at the end of that logic, so that other ranks on the node can see it.
However, as your distribution of ranks is 2 per node for 4 ranks. the first two ranks will find the file, the other two ranks wont (unless you have a shared file system where the code is running). Either way you have to add a barrier as I mentioned before.
For the first two ranks
```
HCL_CONF->SERVER_ON_NODE = true;
std::cout << HLINE << std::endl;
```
for the ranks in other nodes
```
HCL_CONF->SERVER_ON_NODE = false;
std::cout << HLINE << std::endl;
```
This is because the server of rank 2 and 3 are on node 1 not on their node. This will tell HCL to use RPC instead of looking for shared memory. My guess is that is your error.

The rest of the logic would work till your data structure serialization works properly. You might wanna start small to debug the issue. First, have two ranks one server and one client on the same node. Make sure, the config and code work. Then you can try 4 ranks. My intuition is if your config is correct, it would work.

**Comment by hariharan-devarajan** [comment] 2021-05-14 17:37
> As you suggested, I used std::array, and added a readme to briefly describe the example 

As a side comment, the way your serializing is extremely costly. I would recommend bulk serialization instead of element by element.

**Comment by hariharan-devarajan** [comment] 2021-05-14 17:47
> Actually, I want to create a global queue of custom-struct types, e.g., can be called tasks (fixed-sized as usual). The use-case runs with multiple ranks on distributed nodes, each rank has multiple execution threads to perform the tasks. Like the scenario of task-stealing, the current rank could steal tasks from the other ranks. Instead of sending/receiving tasks with 2-sided-MPI operations, I want to try with HCL. So, how do you think? Does this make sense with HCL?

Also, you might wanna consider the following deployment.
rank 0 -> server
rank 1 -> client
rank 2 -> server
rank 3 -> client

Generally, task execution has a payload and task information. In general, it is a good practice to decouple both. 
Utilize hcl::unordered_map for payload
and hcl::queue for instruction.

The unordered map will hash the key and distribute it in the cluster. You can use the same hash to push instructions to the queue of the server which has the payload. This way any task stealing algorithm will just pick up the task from the remote queue and put it in another queue without moving the payload. The payload can be accessed when the data is needed.


Here, the clients will use memory performance (through shared memory) to queue elements to their local server. And the queues can be emptied by servers using a separate thread pool logic (again memory performance).

Only when we need to rebalance the queues (load balancer), we can migrate the tasks from queues it will use the network (i.e. RPC infrastructure).

**Comment by hariharan-devarajan** [comment] 2021-05-20 18:09
Please check this test folder I have an example of complex types.
https://github.com/hariharan-devarajan/hcl/tree/complex_types/test/complex_types

**Comment by ctminh** [comment] 2021-05-21 07:54
Hi @hariharan-devarajan, sorry for the late response, I was busy with something else and didn't focus much on this issue. Thank you very much for your enthusiasm. Yeah, I run a custom type successful with hcl-queue on 2 nodes. It's quite good for me. I have tried something similar to your test folder of complex types, https://github.com/ctminh/hpc-stuff-playground/blob/master/dist-stuff/hcl_examples/custom_queue_test/types.h, e.g.,
```
typedef struct Mattup_StdArr_t {
    std::array<double, SIZE*SIZE> A;
    std::array<double, SIZE*SIZE> B;
    std::array<double, SIZE*SIZE> C;

    Mattup_StdArr_t() {
        for (int i = 0; i < SIZE*SIZE; i++) {
            ...
        }
    }

    template<typename Archive>
    void serialize(Archive& ar) {
        // serialize a bulk of data
        ar & A;
        ar & B;
        ar & C;
    }
} Mattup_StdArr_t;
```
For SIZE, I varied 128, 256, 512, ... but > 128, it throws a runtime-error, maybe, is the size big? Anyway, let me try around with your test folder of complex types. Another point may be from my configs, I run on 2 nodes (4 ranks, 2 ranks per node, R0, R1 on node1 (R0 is the server)| R2, R3 on node 2). Let me try with different configs.

**Comment by ctminh** [comment] 2021-05-21 07:57
> > Actually, I want to create a global queue of custom-struct types, e.g., can be called tasks (fixed-sized as usual). The use-case runs with multiple ranks on distributed nodes, each rank has multiple execution threads to perform the tasks. Like the scenario of task-stealing, the current rank could steal tasks from the other ranks. Instead of sending/receiving tasks with 2-sided-MPI operations, I want to try with HCL. So, how do you think? Does this make sense with HCL?
> 
> Also, you might wanna consider the following deployment.
> rank 0 -> server
> rank 1 -> client
> rank 2 -> server
> rank 3 -> client
> 
> Generally, task execution has a payload and task information. In general, it is a good practice to decouple both.
> Utilize hcl::unordered_map for payload
> and hcl::queue for instruction.
> 
> The unordered map will hash the key and distribute it in the cluster. You can use the same hash to push instructions to the queue of the server which has the payload. This way any task stealing algorithm will just pick up the task from the remote queue and put it in another queue without moving the payload. The payload can be accessed when the data is needed.
> 
> Here, the clients will use memory performance (through shared memory) to queue elements to their local server. And the queues can be emptied by servers using a separate thread pool logic (again memory performance).
> 
> Only when we need to rebalance the queues (load balancer), we can migrate the tasks from queues it will use the network (i.e. RPC infrastructure).

Thanks for your suggestion! Very in detail! Great! I'll try this.

**Comment by ctminh** [comment] 2021-05-21 08:12
Hi, I saw you usually overwrite some operators when defining a struct. Is that important in HCL? I don't have it. I found something interesting in the HCL-paper, instead of using 100% computation at CPU side, you could share a part of it for smart-NICs cores to do. How could you manage that? If so, could we define that at the HCL-config level or user-app level? Or it is fixed as a part of HCL which is associated with data-management operations.

**Comment by hariharan-devarajan** [comment] 2021-05-21 13:31
> For SIZE, I varied 128, 256, 512, ... but > 128, it throws a runtime-error, maybe, is the size big? Anyway, let me try around with your test folder of complex types. Another point may be from my configs, I run on 2 nodes (4 ranks, 2 ranks per node, R0, R1 on node1 (R0 is the server)| R2, R3 on node 2). Let me try with different configs.

No the size should not be an issue I have tested it with GB of size. 
The ranks per server should be 4 and the server on node for R2 and R3 should be false.

**Comment by hariharan-devarajan** [comment] 2021-05-21 15:32
> Hi, I saw you usually overwrite some operators when defining a struct. Is that important in HCL? I don't have it. 

If you are using an ordered data structure you need them. I always define them as a practice.

> I found something interesting in the HCL-paper, instead of using 100% computation at CPU side, you could share a part of it for smart-NICs cores to do. How could you manage that? If so, could we define that at the HCL-config level or user-app level? Or it is fixed as a part of HCL which is associated with data-management operations.

That's part of the libibverbs implementation. I have a prototype library for building RPC over RDMA verbs. In general, the Thallium server runs on the CPU core. What I did in my prototype was that I built the server using the IBverbs work-queue. The work queue executes on the NIC and hence you see those numbers. I am still fixing that prototype for generic cases. Once done, it would be available as a backend in the repo.

**Comment by ctminh** [comment] 2021-05-24 10:45
> > Hi @hariharan-devarajan, sorry for the late response, I was busy with something else and didn't focus much on this issue. Thank you very much for your enthusiasm. Yeah, I run a custom type successful with hcl-queue on 2 nodes. It's quite good for me. I have tried something similar to your test folder of complex types, https://github.com/ctminh/hpc-stuff-playground/blob/master/dist-stuff/hcl_examples/custom_queue_test/types.h, e.g.,
> > ```
> > typedef struct Mattup_StdArr_t {
> >     std::array<double, SIZE*SIZE> A;
> >     std::array<double, SIZE*SIZE> B;
> >     std::array<double, SIZE*SIZE> C;
> > 
> >     Mattup_StdArr_t() {
> >         for (int i = 0; i < SIZE*SIZE; i++) {
> >             ...
> >         }
> >     }
> > 
> >     template<typename Archive>
> >     void serialize(Archive& ar) {
> >         // serialize a bulk of data
> >         ar & A;
> >         ar & B;
> >         ar & C;
> >     }
> > } Mattup_StdArr_t;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For SIZE, I varied 128, 256, 512, ... but > 128, it throws a runtime-error, maybe, is the size big? Anyway, let me try around with your test folder of complex types. Another point may be from my configs, I run on 2 nodes (4 ranks, 2 ranks per node, R0, R1 on node1 (R0 is the server)| R2, R3 on node 2). Let me try with different configs.
> 
> The issues as I see it is the following.
> 
> * in C++ if you allocate large arrays they should use malloc and not cannot be allocated the way you do. Hence, it gives a seg fault in the start of the program.
> * Second, build 1 queue per thousands of node is not scalable and would not be performant. The idea would be have queue per node and then queue_managers can globally combine them. If you want to just do the test case for comparison purposes (wont be performant), you can set server on node false and make sure the server node has enough shared memory allocated to hold the container.
> 
> I am attaching a patch on the complex type which runs your particular data structure.
> 
> [patch_for_working_example_.patch.zip](https://github.com/scs-lab/hcl/files/6523225/patch_for_working_example_.patch.zip)

Hi @hariharan-devarajan, thanks, great! Anyway, I adapted my test as your suggestion with the patch. It worked well, quite good to me. I also changed running with 2 HCL servers, one per node. It sounds good to me. Although it worked well but I am not familiar with the configs before running hcl, e.g., such my test, 4 ranks in total, 2 ranks per node (R0, R1 (server) on Node 1; R2, R3 (server) on Node 2), the config was:
```
[CHECK] R0: is_server=0, my_server=0, num_servers=2, server_on_node=0, mem_allocated=131072000
[CHECK] R1: is_server=1, my_server=0, num_servers=2, server_on_node=1, mem_allocated=131072000
[CHECK] R2: is_server=0, my_server=1, num_servers=2, server_on_node=0, mem_allocated=131072000
[CHECK] R3: is_server=1, my_server=1, num_servers=2, server_on_node=1, mem_allocated=131072000
```
So, what is really my_server and server_on_node? Are the values still 0/1 if we increase the number of ranks? I thought, for example, if R0, R1 on Node1 (R1 is the server), then my_server must point to **the rank id** which is the server. And server_on_node sounds that R0 & R1 on the same node and R1 is the server, then server_on_node of R0 must be true.

**Comment by ctminh** [comment] 2021-05-24 10:53
> NOTE: if you plan to use HCL in your project for task management, I would be happy to help you get a performant deployment of the data structure.
Yeah, I plan to do that, but I want to try such a prototype first with an mxm-tasks-stealing example. Then, we'll plan to integrate hcl for our distributed task-based framework. Thank you, Hariharan! I created a prototype for this here, https://github.com/ctminh/hpc-stuff-playground/tree/master/dist-stuff/hcl_examples/mxm_task_stealing_queue. Does this make sense with HCL? Now, I added multithreading there, but apparently, there's a bug when multiple threads try to push or pop elements with HCL-queues at the same time (not so sure). I'll figure it out, or maybe will try your suggestion by using hcl::unordered_map for payload and hcl::queue for instruction.

**Comment by ctminh** [comment] 2021-05-24 10:57
> > Hi, I saw you usually overwrite some operators when defining a struct. Is that important in HCL? I don't have it.
> 
> If you are using an ordered data structure you need them. I always define them as a practice.
> 
> > I found something interesting in the HCL-paper, instead of using 100% computation at CPU side, you could share a part of it for smart-NICs cores to do. How could you manage that? If so, could we define that at the HCL-config level or user-app level? Or it is fixed as a part of HCL which is associated with data-management operations.
> 
> That's part of the libibverbs implementation. I have a prototype library for building RPC over RDMA verbs. In general, the Thallium server runs on the CPU core. What I did in my prototype was that I built the server using the IBverbs work-queue. The work queue executes on the NIC and hence you see those numbers. I am still fixing that prototype for generic cases. Once done, it would be available as a backend in the repo.

Great! I'm curious and interested in this. Also, read some documents, but no idea how to technically offload kind of computation onto NIC-cores.

**Comment by hariharan-devarajan** [comment] 2021-05-24 15:45
> So, what is really my_server and server_on_node? Are the values still 0/1 if we increase the number of ranks? I thought, for example, if R0, R1 on Node1 (R1 is the server), then my_server must point to **the rank id** which is the server. And server_on_node sounds that R0 & R1 on the same node and R1 is the server, then server_on_node of R0 must be true.

Lets, assume you have 2 nodes with 32 cores each and your application is 64 ranks. If you have clients per server as 16 Then you will have 4 HCL servers indexed 0 to 3 with 2 servers in each node. 
0-15 (including the server rank) will have my_server index as 0
16-31 will have my_server index as 1, and so on.

Therefore, my_server defines which index from server_lists is my own server in the distribution of clients and servers.

Now the server_on_node is for allowing different distributions of clients and servers.
If the my_server index is colocated with the client (as in the above example). Set server_on_node=true (this is the default).
server_on_node=true instructs HCL to use shared memory for intra-node communication (for better performance).


Now let us assume a case where you have 2 nodes of pure clients and a 3rd node of servers. You can deploy both servers and clients with different mpirun (with a shared server_lists) and set server_on_node false. This will instruct HCL not to find shared memory regions locally on the node and utilize the RPC framework to communicate to the server. A use-case of this is in this [paper](http://www.cs.iit.edu/~scs/assets/files/devarajan2020dynamic-abstract.pdf)  where the clients communicate to servers on different nodes.




 





4 processes with rank 1 and 3 being the server.

**Comment by hariharan-devarajan** [comment] 2021-05-24 15:53
> > NOTE: if you plan to use HCL in your project for task management, I would be happy to help you get a performant deployment of the data structure.
> 
> Yeah, I plan to do that, but I want to try such a prototype first with an mxm-tasks-stealing example. Then, we'll plan to integrate hcl for our distributed task-based framework. Thank you, Hariharan! I created a prototype for this here, https://github.com/ctminh/hpc-stuff-playground/tree/master/dist-stuff/hcl_examples/mxm_task_stealing_queue. Does this make sense with HCL? Now, I added multithreading there, but apparently, there's a bug when multiple threads try to push or pop elements with HCL-queues at the same time (not so sure). I'll figure it out, or maybe will try your suggestion by using hcl::unordered_map for payload and hcl::queue for instruction.

Quick pointers,
- The server on a node should be true, based on the explanation I gave before.
- I have never tried OpenMP with Thallium. I had read Thallium uses argobots threads which conflict with OpenMP. One way is to make clients as processes and tests.
- If possible give me a stack trace of the error. I may be able to help you identify the issue. 
- Also can you reproduce it with the earlier test I gave u. Add OpenMP to the mix and send me a patch for me to test.

**Comment by hariharan-devarajan** [comment] 2021-05-24 16:08
> > > Hi, I saw you usually overwrite some operators when defining a struct. Is that important in HCL? I don't have it.
> > 
> > 
> > If you are using an ordered data structure you need them. I always define them as a practice.
> > > I found something interesting in the HCL-paper, instead of using 100% computation at CPU side, you could share a part of it for smart-NICs cores to do. How could you manage that? If so, could we define that at the HCL-config level or user-app level? Or it is fixed as a part of HCL which is associated with data-management operations.
> > 
> > 
> > That's part of the libibverbs implementation. I have a prototype library for building RPC over RDMA verbs. In general, the Thallium server runs on the CPU core. What I did in my prototype was that I built the server using the IBverbs work-queue. The work queue executes on the NIC and hence you see those numbers. I am still fixing that prototype for generic cases. Once done, it would be available as a backend in the repo.
> 
> Great! I'm curious and interested in this. Also, read some documents, but no idea how to technically offload kind of computation onto NIC-cores.

If you utilize verbs' work-queue framework to perform RDMA accesses, you can do this.

**Comment by hariharan-devarajan** [comment] 2021-05-24 16:51
@ctminh If your custom data structure is now working. I would recommend closing this issue. 

For the OpenMPI issue your having. Please update the complex type example with the OpenMPI which can reproduce your issue and create a new issue for that.

Is that ok?

**Comment by ctminh** [comment] 2021-05-24 19:53
Hi @hariharan-devarajan, thank you! Yes, we can close this issue for now. I will update the example with OpenMP, then send it to you.

**Closed** 2021-05-24 19:53 UTC
Labels: question
